
package publicadores;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "categoriaNoExisteException", targetNamespace = "http://publicadores/")
public class CategoriaNoExisteException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CategoriaNoExisteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CategoriaNoExisteException_Exception(String message, CategoriaNoExisteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public CategoriaNoExisteException_Exception(String message, CategoriaNoExisteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicadores.CategoriaNoExisteException
     */
    public CategoriaNoExisteException getFaultInfo() {
        return faultInfo;
    }

}
