
package publicadores;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ingresoInvalidoException", targetNamespace = "http://publicadores/")
public class IngresoInvalidoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IngresoInvalidoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IngresoInvalidoException_Exception(String message, IngresoInvalidoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public IngresoInvalidoException_Exception(String message, IngresoInvalidoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicadores.IngresoInvalidoException
     */
    public IngresoInvalidoException getFaultInfo() {
        return faultInfo;
    }

}
