
package publicadores;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PublicadorImagenesService", targetNamespace = "http://publicadores/")
public class PublicadorImagenesService
    extends Service
{

    private final static URL PUBLICADORIMAGENESSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORIMAGENESSERVICE_EXCEPTION;
    private final static QName PUBLICADORIMAGENESSERVICE_QNAME = new QName("http://publicadores/", "PublicadorImagenesService");

    static {
        URL url = null;
        WebServiceException e = null;
        String home = System.getProperty("user.home");
        String filepath = home + "/.turismoUy/config.properties"; //linux, mac
		//String filepath = home + "\\.turismoUy\\config.properties"; //pc
		String port = "";
	    String dir = "";
	    
	    
	    Properties prop = new Properties();
	    try {
			FileInputStream input = new FileInputStream(filepath);
			try {
				prop.load(input);
				input.close();
			} catch (IOException error) {
				// TODO Auto-generated catch block
				error.printStackTrace();
			}
		} catch (FileNotFoundException error) {
			// TODO Auto-generated catch block
			error.printStackTrace();
		}
	  
	    dir = prop.getProperty("ip");
	    port = prop.getProperty("port");
	            
        try {
            url = new URL(dir+port+"/publicadorImagenes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORIMAGENESSERVICE_WSDL_LOCATION = url;
        PUBLICADORIMAGENESSERVICE_EXCEPTION = e;
    }

    public PublicadorImagenesService() {
        super(__getWsdlLocation(), PUBLICADORIMAGENESSERVICE_QNAME);
    }

    public PublicadorImagenesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORIMAGENESSERVICE_QNAME, features);
    }

    public PublicadorImagenesService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORIMAGENESSERVICE_QNAME);
    }

    public PublicadorImagenesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORIMAGENESSERVICE_QNAME, features);
    }

    public PublicadorImagenesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorImagenesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorImagenes
     */
    @WebEndpoint(name = "PublicadorImagenesPort")
    public PublicadorImagenes getPublicadorImagenesPort() {
        return super.getPort(new QName("http://publicadores/", "PublicadorImagenesPort"), PublicadorImagenes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorImagenes
     */
    @WebEndpoint(name = "PublicadorImagenesPort")
    public PublicadorImagenes getPublicadorImagenesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "PublicadorImagenesPort"), PublicadorImagenes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORIMAGENESSERVICE_EXCEPTION!= null) {
            throw PUBLICADORIMAGENESSERVICE_EXCEPTION;
        }
        return PUBLICADORIMAGENESSERVICE_WSDL_LOCATION;
    }

}
